version: '3'

services:
  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - mynetwork
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    image: wordpress
    volumes:
      - wp_data:/var/www/wordpress
    depends_on:
      - mariadb
    networks:
      - mynetwork
    restart: unless-stopped
    env_file:
      - .env

  nginx:
    container_name: nginx
    build: requirements/nginx
    image: nginx
    depends_on:
      - wordpress
    networks:
      - mynetwork
    restart: unless-stopped
    volumes:
      - wp_data:/var/www/wordpress
    ports:
      - 443:443
    env_file:
      - .env

volumes:
  db_data:
    driver_opts:
      type: none
      device: /home/silim/data/db_data
      o: bind
  wp_data:
    driver_opts:
      type: none
      device: /home/silim/data/wp_data
      o: bind

networks:
  mynetwork:
    driver: bridge
